version: 1
# UPCS Facet: product_type inference rules
rules:
  - product_type: LAPTOP
    domains: [ELECTRONICS]
    keywords: ["노트북", "랩탑", "맥북", "macbook", "그램", "galaxybook", "갤럭시북"]
    tags: ["product_type.laptop"]

  - product_type: SMARTPHONE
    domains: [ELECTRONICS]
    keywords: ["스마트폰", "핸드폰", "휴대폰", "아이폰", "iphone", "갤럭시", "galaxy"]
    tags: ["product_type.smartphone"]

  - product_type: TABLET
    domains: [ELECTRONICS]
    keywords: ["태블릿", "아이패드", "ipad", "갤럭시탭", "galaxytab"]
    tags: ["product_type.tablet"]

  - product_type: EARPHONE
    domains: [ELECTRONICS]
    keywords: ["이어폰", "에어팟", "airpods", "버즈", "buds", "이어버드", "earbuds"]
    tags: ["product_type.earphone"]

  - product_type: HEADPHONE
    domains: [ELECTRONICS]
    keywords: ["헤드폰", "headphone", "헤드셋", "headset"]
    tags: ["product_type.headphone"]

  - product_type: ACCESSORY_CASE
    domains: [ELECTRONICS, FASHION]
    keywords: ["케이스", "커버", "파우치", "가방", "키스킨", "스킨"]
    tags: ["accessory", "product_type.case"]

  - product_type: ACCESSORY_FILM
    domains: [ELECTRONICS]
    keywords: ["필름", "보호필름", "강화유리", "글래스필름"]
    tags: ["accessory", "product_type.protective_film"]

  - product_type: RAMEN
    domains: [FOOD]
    keywords: ["라면", "컵라면", "면류", "신라면", "짜파게티"]
    tags: ["product_type.ramen", "edible"]
